task/urls.py
from django.urls import path

from task.views import (
    index,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    change_task_status,
)

urlpatterns = [
    path("", index, name="index"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task-status/<int:pk>/<str:status>", change_task_status, name="change-task-status"),
]

app_name = "task"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_marks = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_marks", "-created_time"]

    def __str__(self):
        return f"{self.content}: {self.created_time}"

task/forms.py
from django import forms

from task.models import Task, Tag


class TaskForm(forms.ModelForm):

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={"type": "datetime-local"},
        ),
        required=False,
    )

    class Meta:
        model = Task
        fields = ("content", "deadline", "tags", "is_marks")

task/views.py
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect

from task.forms import TaskForm
from task.models import Task, Tag


def index(request):
    task_list = Task.objects.prefetch_related("tags")
    paginator = Paginator(task_list, 3)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "task_list": task_list,
        "page_obj": page_obj,
    }

    return render(request, "task/index.html", context=context)


class TagListView(generic.ListView):
    model = Tag
    template_name = "task/tag_list.html"
    context_object_name = "tag_list"
    queryset = Tag.objects.all().order_by("name")


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = "task/tag_form.html"
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    template_name = "task/tag_form.html"
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "task/tag_confirm_delete.html"
    success_url = reverse_lazy("task:tag-list")


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = "task/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("task:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    template_name = "task/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("task:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "task/task_confirm_delete.html"
    success_url = reverse_lazy("task:index")


def change_task_status(request, pk, status):
    task = Task.objects.get(pk=pk)
    task.is_marks = status
    task.save()
    return redirect("task:index")

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    {% block title %}
      <title>Tasks</title>
    {% endblock %}

   <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" type="image/png" href="/static/images/todolist.png"/>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-2">

          {% block sidebar %}
            {% include "includes/sidebar.html" %}
          {% endblock %}

        </div>

        <div class="col-sm-10">

          {% block content %}{% endblock %}

          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}

        </div>

      </div>
    </div>
  </body>
</html>

templates/includes/pagination.html
<div class="container">

  {% if page_obj.has_other_pages %}
  <ul class="pagination">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}

  </ul>
  {% endif %}

</div>

templates/includes/sidebar.html
<ul class="sidebar-nav">
  <li class="list-group-item"><a href="{% url 'task:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'task:tag-list' %}">Tags</a></li>
</ul>

templates/task/index.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <h1>
      TODO list
      <a href="{% url 'task:task-create' %}" class="btn btn-primary link-to-page">Add task</a>
      <hr>
    </h1>
  </div>
    <br><br>

  {% for task in page_obj %}
    <div class="container">
      <h5>
        {{ task.content }}

        {% if task.is_marks %} &nbsp;
          <small style="color: #008000"><em>Done</em></small>
          <button class="btn btn-secondary link-to-page"
                  onclick="location.href='{% url 'task:change-task-status' task.pk False %}'">
            Undo
          </button>

        {% else %} &nbsp;
          <small style="color: #DC143C"><em>Not done</em></small>
          <button class="btn btn-success link-to-page"
                  onclick="location.href='{% url 'task:change-task-status' task.pk True %}'">
            Complete
          </button>

        {% endif %}
      </h5>

      <p>Created: <em>{{ task.created_time }}</em>  &nbsp;
        {% if task.deadline %}
          <span class="text">Deadline: <em>{{ task.deadline }}</em></span>
        {% endif %}
      </p>

      <p>Tags:
        {% for tag in task.tags.all %} &nbsp;
          {{ tag.name }}
        {% endfor %} &nbsp;
        <a href="{% url 'task:task-update' pk=task.id %}">Update</a>
        <a href="{% url 'task:task-delete' pk=task.id %}" style="color: red">Delete</a>
      </p>
      <hr>
      <br>
    </div>
  {% endfor %}

{% endblock %}

templates/task/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <div class="container">
    <h1>Delete tag</h1>
    <hr>
    <p>
      Are you sure you want to delete the tag: <em>{{ tag }}</em>?
    </p>

    <form action="" method="post">
      {% csrf_token %}
      <br>
      <hr>
      <input class="btn btn-danger" type="submit" value="Yes, delete">
      <a href="{% url 'task:tag-list' %}" class="btn btn-secondary">No, cancel</a>
    </form>
  </div>

{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="container">
    <h1>
      {{ object|yesno:"Update,Add" }} tag
    </h1>
    <hr>

    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <hr>
      <input class="btn btn-primary" type="submit" value="Submit">
      <input class="btn btn-secondary" type="reset" value="Clear">
    </form>
  </div>

{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}

{% block content %}

  <div class="container">
    <h1>
      Tags
      <a href="{% url 'task:tag-create' %}" class="btn btn-primary link-to-page">Add tag</a>
    </h1>
    <br>

      {% if tag_list %}
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a href="{% url 'task:tag-update' pk=tag.id %}" class="btn btn-secondary">Update</a>
          </td>
          <td>
            <a href="{% url 'task:tag-delete' pk=tag.id %}" class="btn btn-danger">Delete</a>
          </td>
        </tr>
      {% endfor %}
      </table>
      {% endif %}
      <hr>

  </div>

{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <div class="container">
    <h1>Delete task</h1>
    <hr>
    <p>
      Are you sure you want to delete the task: <em>{{ task.content }}</em>?
    </p>

    <form action="" method="post">
      {% csrf_token %}
      <br>
      <hr>
      <input class="btn btn-danger" type="submit" value="Yes, delete">
      <a href="{% url 'task:index' %}" class="btn btn-secondary">No, cancel</a>
    </form>
  </div>

{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="container">
    <h1>
      {{ object|yesno:"Update,Add" }} task
    </h1>
    <hr>

    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <hr>
      <input class="btn btn-primary" type="submit" value="Submit">
      <input class="btn btn-secondary" type="reset" value="Clear">
    </form>
  </div>

{% endblock %}